add flag to dump from local production

diff --git a/bin/restore_db b/bin/restore_db
--- a/bin/restore_db
+++ b/bin/restore_db
@@ -13,16 +13,18 @@ FILE defaults to "latest.dump" if not provided.
                 overwrites FILE. Requires a git
                 heroku remote and authenticated session
     -d          restore development db
+    -l          capture backup from local production
     -p          restore production db
 EOF
 }
 
 capture=false
+local=false
 development=false
 production=false
 
 OPTIND=1
-while getopts hcdp opt; do
+while getopts hcdlp opt; do
   case $opt in
     h)
       show_help 2>&1
@@ -33,6 +35,9 @@ while getopts hcdp opt; do
       ;;
     d)
       development=true
+      ;;
+    l)
+      local=true
       ;;
     p)
       production=true
@@ -53,10 +58,21 @@ shift "$((OPTIND-1))" # Shift off the options and optional --.
 # Everything that's left in "$@" is a non-option.  In our case, a FILE to process.
 FILE=${@:-'latest.dump'}
 
+if [ "$capture" = true ] && [ "$local" = true ]
+then
+  echo "Cannot use both -c and -l flags simultaneously."
+  exit 1
+fi
+
 if [ "$capture" = true ]
 then
   heroku pg:backups:capture
   heroku pg:backups:download -o "$FILE"
+fi
+
+if [ "$local" = true ]
+then
+  PGPASSWORD=simrep pg_dump -Fc --no-acl --no-owner -h localhost -U simrep simrep_production > "$FILE"
 fi
 
 if [ "$development" = true ]
