bin and infra updates
force redis to be in-memory
less noisy logic for worker/tests

diff --git a/bin/start_test b/bin/start_test
--- a/bin/start_test
+++ b/bin/start_test
@@ -2,11 +2,19 @@
 
 curl -I $APP_CONTAINER_URL
 
-while ! [ "$?" = "0" ]; do
-  echo "Could not connect to web container. Sleeping.";
+if [[ ! "$?" = "0" ]]; then
+  echo "Could not connect to app container. Sleeping 60 seconds.";
+  sleep 60;
+  curl -I $APP_CONTAINER_URL
+fi
+
+while [[ ! "$?" = "0" ]]; do
+  echo "Could not connect to app container. Sleeping 15 seconds.";
   sleep 15;
   curl -I $APP_CONTAINER_URL
 done
 
-bundle exec rails db:setup
+echo "Connected. Starting tests."
+
+bundle exec rails db:test:prepare
 bundle exec rspec spec/
diff --git a/bin/start_worker b/bin/start_worker
--- a/bin/start_worker
+++ b/bin/start_worker
@@ -2,10 +2,18 @@
 
 curl -I $APP_CONTAINER_URL
 
-while ! [ "$?" = "0" ]; do
-  echo "Could not connect to web container. Sleeping.";
+if [[ !"$?" = "0" ]]; then
+  echo "Could not connect to web container. Sleeping 60 seconds.";
+  sleep 60;
+  curl -I $APP_CONTAINER_URL
+fi
+
+while [[ ! "$?" = "0" ]]; do
+  echo "Could not connect to web container. Sleeping 15 seconds.";
   sleep 15;
   curl -I $APP_CONTAINER_URL
 done
+
+echo "Connected. Starting workers."
 
 bundle exec sidekiq -C config/sidekiq.yml
