spacing and typos in start_worker

diff --git a/bin/start_worker b/bin/start_worker
--- a/bin/start_worker
+++ b/bin/start_worker
@@ -2,14 +2,14 @@
 
 curl -I $APP_CONTAINER_URL
 
-if [[ !"$?" = "0" ]]; then
-  echo "Could not connect to web container. Sleeping 60 seconds.";
+if [[ ! "$?" = "0" ]]; then
+  echo "Could not connect to app container. Sleeping 60 seconds.";
   sleep 60;
   curl -I $APP_CONTAINER_URL
 fi
 
 while [[ ! "$?" = "0" ]]; do
-  echo "Could not connect to web container. Sleeping 15 seconds.";
+  echo "Could not connect to app container. Sleeping 15 seconds.";
   sleep 15;
   curl -I $APP_CONTAINER_URL
 done
